server: "hub.lambdatest.com"
user: "LT_USERNAME"
key: "LT_ACCESS_KEY"

common_caps:
  "build": "RSpec Selenium Demo"

browser_caps:
  -
    "browserName": "chrome"
    "version": "latest"
    "platform": "Windows 10"
