server: ENV["HOST"]
user: ENV["LT_USERNAME"]
key: ENV["LT_ACCESS_KEY"]

common_caps:
  "build": "RSpec Selenium Demo"

browser_caps:
  -
    "browserName": "chrome"
    "version": "latest"
    "platform": "Windows 10"
